### PR TITLE
feat(search): [MAG-3266] Search button component ONLY!

### PR DESCRIPTION
**Pull request by matthill8286**
# <https://filtered-ewb.atlassian.net/browse/MAG-3266 / Search>

## TL;DR

-  Search input, styled search, tests, stories, types and extended theme to create default Icon theme

## Details

Checklist / Reminders:

-   [x] Documentation / Story is created / adapted
-   [x] Unit tests
-   [x] CSS changes are BEM-compliant

Screenshot 2020-12-11 at 19 31 09

### CODE REVIEW

**Comment by tricaalexandru** [comment]
@matthill8286 the result component looks incomplete in the screenshots:

Screenshot 2020-12-12 at 11 10 00

1.The provider | Type | Primary competency are missing.
2. There is a separator between results
3. This I'm unsure as I can't tell from the screenshot,,but in the design the result component wil be spanning across the entirety of the grid not only the size of the search



O ther than that from the designs I don't understand the highlight. Because when you press an item it should just go to it.

**Comment by matthill8286** [comment]
> @matthill8286 the result component looks incomplete in the screenshots:
> 
> Screenshot 2020-12-12 at 11 10 00
> 
> 1.The provider | Type | Primary competency are missing.
> 2. There is a separator between results
> 3. This I'm unsure as I can't tell from the screenshot,,but in the design the result component wil be spanning across the entirety of the grid not only the size of the search
> 
> O ther than that from the designs I don't understand the highlight. Because when you press an item it should just go to it.

@tricaalexandru The ticket is for the Search Bar component so i'm a bit confused why you are expecting all those other parts you have mentioned, the search result component is in a separate subtask because it's a sub component of the Header which the parent ticket is for. As is the filter, links, profile dropdown etc...

**Comment by tricaalexandru** [comment]
@matthill8286 sorry that was my bad. Can I merge?

**Review by tricaalexandru — APPROVED** [review]

**Comment by matthill8286** [comment]
@tricaalexandru Closing as this branch was merged into the other search results branch

**Pull request closed without merging**
