### PR TITLE
[MAG-3300] Footer styling

### PR DESCRIPTION
**Pull request by philjonasfiltered**
# <JIRA issue / Title>

## TL;DR

-   changed styling
-   swapped `Link` list with `LinkList`

image

## Details

Checklist / Reminders:

-   [ ] Documentation / Story is created / adapted
-   [ ] Unit tests
-   [ ] CSS changes are BEM-compliant

### CODE REVIEW

**Comment by matthill8286** [comment]
@philjonasfiltered If you merge master into your branch you'll find i've added more configuration for your LinksList component, you can now control the size, color and padding. 

`<LinkList color="grey4" size="xs" padding="0 sm" />`

**Comment by matthill8286** [comment]
@philjonasfiltered Have you updated the LinkList size padding and color props??

**Comment by philjonasfiltered** [comment]
> @philjonasfiltered Have you updated the LinkList size padding and color props??

@matthill8286 I noticed now that the links were a bit apart from one another and that the `powered by` line should not be under the links. 👍

**Comment by matthill8286** [comment]
@philjonasfiltered I have fixed these in https://github.com/excelWithBusiness/TS-Filtered-SC-Components/pull/86 have a look at the PR for the way to do it ideally 👍  Hopefully gives you some ideas.

**Comment by philjonasfiltered** [comment]
> @philjonasfiltered I have fixed these in #86 have a look at the PR for the way to do it ideally 👍 Hopefully gives you some ideas.

I was reading your PR and was about to ask you @matthill8286 as I noticed the overlap 😅 Cheers 👍

**Pull request closed without merging**
